BUILDLIB:=TYRICO

CREATEMOD:
	system "CRTCPPMOD MODULE(${BUILDLIB}/ileBridge) SRCSTMF('$(CURDIR)/ileBridge.cpp') OPTION(*EVENTF) SYSIFCOPT(*IFS64IO) DBGVIEW(*SOURCE) TERASPACE(*YES *TSIFC) STGMDL(*SNGLVL) DTAMDL(*p128) DEFINE(DEBUG_ENABLED) OUTPUT(*PRINT) TGTCCSID(*JOB)" 


CREATEPGM: CREATEMOD
	system "CRTPGM PGM(${BUILDLIB}/ileBridge) MODULE(${BUILDLIB}/ileBridge) ACTGRP(*CALLER)"

CREATEMODK:
	system "CRTCPPMOD MODULE(${BUILDLIB}/ileBridgeK) SRCSTMF('$(CURDIR)/ileBridgeK.cpp') OPTION(*EVENTF) SYSIFCOPT(*IFS64IO) DBGVIEW(*SOURCE) TERASPACE(*YES *TSIFC) STGMDL(*SNGLVL) DTAMDL(*p128) DEFINE(DEBUG_ENABLED) OUTPUT(*PRINT) TGTCCSID(*JOB)" 


CREATEPGMK: CREATEMODK
	system "CRTPGM PGM(${BUILDLIB}/ileBridgeK) MODULE(${BUILDLIB}/ileBridgeK) ACTGRP(*CALLER)"


all: CREATEPGM CREATEPGMK